[build]
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/gallery.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/assets/logo.png"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
from = "/api/surveyMailFormSender"
to = "/.netlify/functions/surveyMailFormSender"
status = 200

[[redirects]]
from = "/api/contactMailFormSender"
to = "/.netlify/functions/contactMailFormSender"
status = 200